#!/bin/sh

keyboard_id=9 # use 'xinput list' to find your keyboard's id. uzu 'xinput list' por trovi la id-numeron de via klavaro.

# 0. be ready to die gracefully 
dzen2_pid_file=/tmp/iksilo-dzen2-pid
die() { setxkbmap -option; kill $(cat $dzen2_pid_file); pkill -KILL -f iksilo; }
trap die INT HUP TERM; [ "$1" = "stop" ] && die

# 1. add the necessary keyboard options 
setxkbmap -option lv3:ralt_switch,esperanto:qwerty

# 2. simulate an associative array using variables: array_38=a array_39=s array_40=d etc.
xmodmap -pke >/tmp/keymap
while read line; do
	keycode="$(echo $line | cut -d' ' -f 2)"
	key="$(echo $line | cut -d' ' -f 4)"
	eval array_"$keycode"="$key"
done </tmp/keymap
rm /tmp/keymap

# 3. create indicator if dzen2 is installed
if which dzen2 >/dev/null; then
	echo "IKSO" | dzen2 -fg "white" -bg "green" -w 40 -h 20 -x 1235 -y 755 -p -e '' & echo $! >$dzen2_pid_file
fi

# 4. keep track of last two keypresses, replacing them with Esperanto character when appropriate
replace() { xdotool key BackSpace BackSpace "$1"; }
memory="--"

xinput test $keyboard_id | stdbuf -oL awk '/press/ {print $3}' | while read keycode; do
	key=$(eval echo \$array_$keycode)
	memory=$(echo "${memory}${key}" | grep -o '..$')
	case $memory in
		cx) replace ISO_Level3_Shift+c ;;
		gx) replace ISO_Level3_Shift+g ;;
		hx) replace ISO_Level3_Shift+h ;;
		jx) replace ISO_Level3_Shift+j ;;
		sx) replace ISO_Level3_Shift+s ;;
		ux) replace ISO_Level3_Shift+u ;;
	esac
done
